apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-y0tx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-y0tx
    app.kubernetes.io/part-of: tkrw-pr714-0075-0040-app
  name: devfile-sample-y0tx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-y0tx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-y0tx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0040-tenant/tkrw-pr714-0075-0040-app/devfile-sample-y0tx@sha256:eb0e633fdaf93af3a524fffab44992425a9fb9ea22a527d9dc5739b2a2b0a57a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
